---
- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=installed update_cache=yes
  sudo: yes
  notify: Restart elasticsearch

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit
