---
- name: Add Elasticsearch repository.
  when: ansible_os_family == 'RedHat'
  copy:
    src: files/elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch.
  when: ansible_os_family == 'RedHat'
  yum: pkg=elasticsearch state=installed update_cache=yes
  sudo: yes

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest extra_args='--proxy {{ proxy_env.http_proxy }}'
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  when: ansible_os_family == 'RedHat'
  sudo: yes
  notify: Restart elasticsearch

- name: Creates ES Cluster (master) directory
  file: >
    path={{elk_elasticsearch.node.master.path}}
    state=directory
    owner={{elk_elasticsearch.owner}}
    group={{elk_elasticsearch.group}}
    mode=0775
    recurse=yes

- name: ES Cluster (master) config file
  template:
    src=elastic.master.yml.j2
    dest={{elk_elasticsearch.node.master.path}}/elasticsearch.yml
    owner=root group=root mode=644
  when: ansible_os_family == 'RedHat'
  sudo: yes

- name: Creates ES Cluster (slave) directory
  file: >
    path={{elk_elasticsearch.node.slave.path}}
    state=directory
    owner={{elk_elasticsearch.owner}}
    group={{elk_elasticsearch.group}}
    mode=0775
    recurse=yes

- name: ES Cluster (slave) config file
  template:
    src=elastic.slave.yml.j2
    dest={{elk_elasticsearch.node.slave.path}}/elasticsearch.yml
    owner=root group=root mode=644
    when: ansible_os_family == 'RedHat'
    sudo: yes

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit
