---
- name: Add Logstash repository.
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash.
  yum: pkg={{ item }} state=installed
  with_items:
    - logstash
    - logstash-contrib
  sudo: yes
  notify: Restart logstash

- name: Logstash conf file
  template:
    src={{ item.src }}
    dest=/etc/logstash/conf.d/{{ item.dest }}
    owner=root group=root mode=644
  with_items: elk_logstash.configs
  sudo: yes
  notify: Restart logstash

- name: Logstash pattern files
  template:
    src={{ item.src }}
    dest=/opt/logstash/patterns/{{ item.dest }}
    owner=root group=root mode=644
  with_items: elk_logstash.patterns
  sudo: yes
  when: elk_logstash.patterns is defined
  notify: Restart logstash

- name: Make monit to look after Logstash
  template:
    src=logstash.monitrc.conf.j2
    dest=/etc/monit.d/logstash.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit
