---
- name: Include OS-specific variables
  include_vars: "RedHat.yml"

- name: Install common yum packages
  yum: pkg={{ item }} state=latest update_cache=true
  with_items: elk_common_packages
  sudo: yes

- name: Monit conf file
  copy:
    src=monitrc
    dest=/etc/monit/monitrc
    owner=root group=root mode=600
  sudo: yes
  notify: Restart monit

- name: Install Java
  include: java.yml

- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present
  sudo: yes

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: logstash.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml
