---
- name: Load RedHat variables
  include_vars: "RedHat.yml"

- name: Install common yum packages
  yum: pkg={{ item }} state=latest update_cache=true
  with_items: elk_common_packages
  sudo: yes

- name: Monit conf file
  copy:
    src=files/monitrc
    dest=/etc/monit/monitrc
    owner=root group=root mode=600
  sudo: yes
  notify: Restart monit

- name: Install Java
  include: java.yml

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml
