---
- name: Add repo file
  template: src=files/nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

- name: Add repo key
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx sha256sum=dcc2ed613d67b277a7e7c87b12907485652286e199c1061fb4b3af91f201be39 force=yes

- name: Add repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx owner=root group=root mode=0644

- name: Add repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx

- name: Install Nginx
  yum: name=nginx enablerepo=nginx state=present

- name: Disable default servers
  file:
    path=/etc/nginx/conf.d/{{ item.path }}
    state=absent
  with_items:
    - { path: 'default.conf' }
    - { path: 'example_ssl.conf' }
  sudo: yes

- name: Make monit to look after nginx
  template:
    src=nginx.monitrc.conf.j2
    dest=/etc/monit/conf.d/nginx.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit
